# 服务器配置
server:
   port: 8000
   sessionTimeout: 45
   contextPath: /

spring:
   freemarker:
      #req访问request
      request-context-attribute: req
      #后缀名 .ftl
      suffix: .ftl
      content-type: text/html; charset=utf-8
      enabled: true
      cache: false
      #模板加载路径 按需配置
      template-loader-path: classpath:/templates/
      charset: UTF-8
      allow-request-override: false
      check-template-location: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      settings:
         #数字格式化，无小数点
         number_format: '0.##'
   # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
   resources:
#     static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
   chain:
      cache: false #resources缓存