# 服务器配置
server:
   port: 8000
   sessionTimeout: 45
   contextPath: /

#mybatis
mybatis-plus:
   global-config:
      # 数据库相关配置
      db-config:
         #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
         id-type: id_worker
         #驼峰下划线转换
         column-underline: true
         #数据库大写下划线转换
         #capital-mode: true
         db-type: MYSQL
      #刷新 mapper 调试神器
      refresh: true
   # 原生配置
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      default-fetch-size: 100
      default-statement-timeout: 30
